### ISSUE TITLE
Warnings on split functions in Bro 2.4+

### ISSUE THREAD

**Issue by mhofstra** [corelight/bro-drwatson#1] opened 2017-05-05 09:35 UTC
Running these scripts is throwing warnings in recent versions of Bro because it uses deprecated functions:

warning in /path/to/drwatson/./bro/./main.bro, line 123: deprecated (split_n)
warning in /path/to/drwatson/./bro/./main.bro, line 145: deprecated (split_n)
warning in /path/to/drwatson/./bro/./main.bro, line 191: deprecated (split1)
warning in /path/to/drwatson/./bro/./main.bro, line 205: deprecated (split1)
warning in /path/to/drwatson/./bro/./main.bro, line 208: deprecated (split_all)

https://www.bro.org/sphinx/install/release-notes.html#id4 has deprecation notes

**Comment by sethhall** [comment] 2017-07-17 19:00
Thanks for the note.  It's all fixed now.  There were even larger issues that had been caused by a change to vectors in Bro.  The package has a test now at least which should prevent problems like that in the future.

It's also available in the Bro Package Manager now.

**Closed as completed by sethhall** 2017-07-17 19:00 UTC
